import './monacoEnvironment';
import { loader } from '@monaco-editor/react';
import * as monaco from 'monaco-editor';

loader.config({ monaco });

/** Monaco themes aligned with the app chrome in both dark and light modes. */
monaco.editor.defineTheme('void-dark', {
	base: 'vs-dark',
	inherit: true,
	rules: [],
	colors: {
		'editor.background': '#10161b',
		'editor.foreground': '#d2dbe0',
		'editorGutter.background': '#10161b',
		'editorLineNumber.foreground': '#5f707c',
		'editorLineNumber.activeForeground': '#d9eef0',
		'editorCursor.foreground': '#37d6d4',
		'editor.selectionBackground': '#24545d66',
		'editor.inactiveSelectionBackground': '#1f465066',
		'editor.selectionHighlightBackground': '#24545d33',
		'editor.wordHighlightBackground': '#24545d22',
		'editor.wordHighlightStrongBackground': '#ff9d5922',
		'editor.lineHighlightBackground': '#162128',
		'editor.lineHighlightBorder': '#00000000',
		'editorIndentGuide.background1': '#26323c',
		'editorIndentGuide.activeBackground1': '#3a4e5a',
		'editorWhitespace.foreground': '#32414c',
		'editorBracketMatch.background': '#37d6d422',
		'editorBracketMatch.border': '#37d6d455',
		'editorOverviewRuler.border': '#00000000',
		'minimap.background': '#10161b',
		'minimap.selectionHighlight': '#37d6d433',
		'minimap.findMatchHighlight': '#ff9d5944',
		'minimap.errorHighlight': '#ff7b8644',
		'minimap.warningHighlight': '#ffb05b44',
		'minimapSlider.background': '#4b5f6d55',
		'minimapSlider.hoverBackground': '#5d748366',
		'minimapSlider.activeBackground': '#6f889977',
		'peekView.border': '#2b8f96',
		'peekViewEditor.background': '#121a20',
		'peekViewResult.background': '#151f26',
		'peekViewTitle.background': '#172129',
		'editorWidget.background': '#162028',
		'editorWidget.border': '#31404b',
		'dropdown.background': '#162028',
		'dropdown.border': '#31404b',
		'input.background': '#131c23',
		'input.foreground': '#d2dbe0',
		'input.border': '#31404b',
		'list.hoverBackground': '#1c2a33',
		'list.activeSelectionBackground': '#1d5960',
		'list.activeSelectionForeground': '#effcfc',
		'list.inactiveSelectionBackground': '#1a3035',
		'scrollbar.shadow': '#00000000',
		'scrollbarSlider.background': '#44556388',
		'scrollbarSlider.hoverBackground': '#5a6c7bcc',
		'scrollbarSlider.activeBackground': '#708493cc',
		'diffEditor.insertedTextBackground': '#59d9b826',
		'diffEditor.removedTextBackground': '#ff7b8624',
	},
});

monaco.editor.defineTheme('void-light', {
	base: 'vs',
	inherit: true,
	rules: [],
	colors: {
		'editor.background': '#f7fafc',
		'editor.foreground': '#213040',
		'editorGutter.background': '#f7fafc',
		'editorLineNumber.foreground': '#95a2b6',
		'editorLineNumber.activeForeground': '#223141',
		'editorCursor.foreground': '#1ea7b5',
		'editor.selectionBackground': '#b8ebf080',
		'editor.inactiveSelectionBackground': '#c9edf066',
		'editor.selectionHighlightBackground': '#d8f4f633',
		'editor.wordHighlightBackground': '#d8f4f633',
		'editor.wordHighlightStrongBackground': '#ffd6bb44',
		'editor.lineHighlightBackground': '#eef5f8',
		'editor.lineHighlightBorder': '#00000000',
		'editorIndentGuide.background1': '#d6e0e7',
		'editorIndentGuide.activeBackground1': '#b8c8d3',
		'editorWhitespace.foreground': '#d6e0e7',
		'editorBracketMatch.background': '#b8ebf04d',
		'editorBracketMatch.border': '#6dc9d355',
		'editorOverviewRuler.border': '#00000000',
		'minimap.background': '#f7fafc',
		'minimap.selectionHighlight': '#9de1e866',
		'minimap.findMatchHighlight': '#ffc79b66',
		'minimap.errorHighlight': '#f2a3aa66',
		'minimap.warningHighlight': '#ffc27f66',
		'minimapSlider.background': '#aab8c555',
		'minimapSlider.hoverBackground': '#8fa0ae66',
		'minimapSlider.activeBackground': '#75889677',
		'peekView.border': '#49b8c4',
		'peekViewEditor.background': '#f4fafb',
		'peekViewResult.background': '#eef6f8',
		'peekViewTitle.background': '#e8f3f6',
		'editorWidget.background': '#fbfdfe',
		'editorWidget.border': '#cfdbe3',
		'dropdown.background': '#fbfdfe',
		'dropdown.border': '#cfdbe3',
		'input.background': '#ffffff',
		'input.foreground': '#213040',
		'input.border': '#cfdbe3',
		'list.hoverBackground': '#edf5f7',
		'list.activeSelectionBackground': '#d5f4f3',
		'list.activeSelectionForeground': '#163138',
		'list.inactiveSelectionBackground': '#e8f1f4',
		'scrollbar.shadow': '#00000000',
		'scrollbarSlider.background': '#b7c3cf99',
		'scrollbarSlider.hoverBackground': '#9eacbacc',
		'scrollbarSlider.activeBackground': '#8595a5cc',
		'diffEditor.insertedTextBackground': '#59d9b81f',
		'diffEditor.removedTextBackground': '#ff7b8618',
	},
});
